### ISSUE TITLE
Kotlin port of Chocobar

### ISSUE THREAD

**Issue by JamesEllerbee** [Pradyuman7/ChocoBar#25]
**Is your feature request related to a problem? Please describe.**
New feature request

**Describe the solution you'd like**
Kotlin port of Chocobar

**Describe alternatives you've considered**
Upgrading the project to java 8

**Additional context**
I would like to work this

**Comment by Pradyuman7** [comment]
Hey @JamesEllerbee, that sounds great. Please feel free to work on this one. Let me know if you have any questions!

**Comment by JamesEllerbee** [comment]
> 
> 
> Hey @JamesEllerbee, that sounds great. Please feel free to work on this one. Let me know if you have any questions!

@Pradyuman7 Do you think the best way to achieve this would be to create a new module `chocobarKotlin` in this project that imports the necessary kotlin sdk?

**Comment by Pradyuman7** [comment]
Hm, I guess that should be fine for now. We can work on separating it later on.
