### ISSUE TITLE
Minimum SDK

### ISSUE THREAD

**Issue by coolmyll** [Pradyuman7/ChocoBar#3]
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.github.Pradyuman7:ChocoBar:V1.0] C:\Users\Cool\.gradle\caches\transforms-1\files-1.1\jetified-ChocoBar-V1.0.aar\2df20e04cd68d6f9490200ae77845214\AndroidManifest.xml as the library might be using APIs not available in 14
> 	Suggestion: use a compatible library with a minSdk of at most 14,
> 		or increase this project's minSdk version to at least 15,
> 		or use tools:overrideLibrary="com.pd.chocobar" to force usage (may lead to runtime failures)

So is the minimum sdk requirement 14 or 15?

**Comment by Pradyuman7** [comment]
Sorry for that! It's minimum 15. API 15+. Thank you for pointing that out.
