### ISSUE TITLE
Failed to resolve: com.github.Pradyuman7:ChocoBar:V1.0

### ISSUE THREAD

**Issue by shahirislam** [Pradyuman7/ChocoBar#35]
implementation 'com.github.Pradyuman7:ChocoBar:V1.0'
    
![chocoBar](https://user-images.githubusercontent.com/64928504/211914892-2ca87a80-ff56-4d6d-a46c-933996e7f3b5.png)

**Comment by Pradyuman7** [comment]
This can happen if you don't have the jitpack repository. Do you have jipack repository in your gradle?

**Comment by Pradyuman7** [comment]
Closing for now, feel free to reopen if the issue comes up again
